# Recipe directory
#
# The use of '~' (tilde expansion) is supported.
recipe_dir = "./recipes"

# Editor command to edit recipes
#
# The editor should be able to wait for the files to be closed before returning.
# This might be achieved with additional command line parameters.
#
# E.g. for Sublime Text use:
# editor = ["subl", "--wait", "--"]
#
# CLI editors should work fine.
#
# For syntax highlighting have a look at:
# https://github.com/tobx/sweet-potator/tree/main/assets/grammars
editor = ["vim"]

# Valid image file extensions
image_file_extensions = [
    "apng",
    "avif",
    "gif",
    "jfif",
    "jpeg",
    "jpg",
    "pjp",
    "pjpeg",
    "png",
    "svg",
    "webp",
]

# HTML template
[templates.html]
extension = "html"
file_name_filter = "slugify"
# escape = true
# language = "en"

# Markdown template
[templates.markdown]
extension = "md"
# file_name_filter = "sanitize"
# escape = true
# language = "en"
